### ISSUE TITLE
Update the Debug Colours to Show Nested Depth

### ISSUE THREAD

**Issue by OpenSauce** [yohamta/furex#21]
Currently the debug flag will paint the view and it's children in separate colours. It would be cool if there were different colours that shows the depth of nested children.

**Comment by yohamta** [comment]
That’s truly necessary. How about using [RotateHue](https://pkg.go.dev/github.com/hajimehoshi/ebiten#RotateHue) to change the color for each nested levels?

**Comment by OpenSauce** [comment]
Sounds good to me - I'll take a look

**Comment by yohamta** [comment]
Thank you!
