### ISSUE TITLE
How to create hover effect for button?

### ISSUE THREAD

**Issue by makarychev13** [yohamta/furex#30]
Hi. I want to realize the hover effect on the button ([example](https://miro.medium.com/max/4800/1*r6bRimc8cTfy_Up_3wQU0g.gif)). Is it possible?

I [tried](https://go.dev/play/p/JfEHPYOYuYI) to implement the `MouseHandler`, but i can't handle the mouse leave event.

Could you help me, please.

P. S. Cool lib. Thanks a lot.

**Comment by yohamta** [comment]
Hi, thanks for using the furex :)

I think it is not possible at this moment, but that functionality can be added fairly easily. What do you think about the below interface?

```go
type MouseEnterHandler interface {
	HandleMouseEnter(x, y int) bool
}
type MouseLeaveHandler interface {
	HandleMouseLeave() bool
}
```

**Comment by makarychev13** [comment]
It looks cool, I like it!

**Comment by yohamta** [comment]
@makarychev13 Hi, the `MouseEnterLeaveHandler` is now available in `v2.2.0`. Thanks!
https://github.com/yohamta/furex/blob/main/handler.go#L64

**Comment by makarychev13** [comment]
Thanks!

**Comment by yohamta** [comment]
Welcome!
