### ISSUE TITLE
Automatically resizing screen sections

### ISSUE THREAD

**Issue by hak33m16** [yohamta/furex#38]
Hi, this project seems like a really great idea. I'm trying to incorporate it into something I'm doing, but I'm having trouble with some basic things. For example, I'm trying to create an editor that has 3 sections to it, it would look something like this:

```
---------------------------
|                         |
---------------------------
|                         |
|                         |
|                         |
|-------------------------|
|                         |
|-------------------------|
```

But the problem is that when I create a view, similar to what's in the example code, I need to give it a width and height. So the important bit of my code looks like this:

```
	g.gameUI = &furex.View{
		Width:        g.screen.Width,
		Height:       g.screen.Height,
		Direction:    furex.Row,
		Justify:      furex.JustifyCenter,
		AlignItems:   furex.AlignItemCenter,
		AlignContent: furex.AlignContentCenter,
		Wrap:         furex.Wrap,
		
	}

	g.gameUI.AddChild(&furex.View{
		Width:  g.screen.Width,
		Height: 50,
		Handler: &Box{
			Color: color.RGBA{0x81, 0xb6, 0x22, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Width:  g.screen.Width,
		Height: g.screen.Height - 50 - 50,
		Handler: &Box{
			Color: color.RGBA{0x81, 0xb6, 0x22, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Width:  g.screen.Width,
		Height: 50,
		Handler: &Box{
			Color: color.RGBA{0x81, 0xb6, 0x22, 0xff},
		},
	})
```

So the real question is, how would you go about making the 3 boxes automatically adjust to the size of the screen, instead of having them be static when I resize the window?

As an aside, there are quite a few undocumented features on the furex.View object that I'm not sure what they do, and if they could help with this. For example, Left Top Grow and Shrink didn't seem to have examples or any documentation around what they do

**Comment by yohamta** [comment]
hey @hak33m16 👋
Thanks for the detailed question!
I think [View.UpdateWithSize](https://pkg.go.dev/github.com/yohamta/furex/v2#View.UpdateWithSize) could be useful for that purpose. You can call it on every frame so the view size changes automatically. Hope it answers your question.

**Comment by hak33m16** [comment]
Hmmm, I may be missing something, but that doesn't really seem to help here. The general flow according to your [examples here](https://github.com/yohamta/furex/blob/v2.2.3/examples/game/main.go) goes something like:

```
package main

import (
	"image"
	"image/color"
	"sync"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
	"github.com/yohamta/furex/v2"
)

type ScreenSize struct {
	Width  int
	Height int
}

type Game struct {
	initOnce   sync.Once
	screenSize ScreenSize
	gameUI     *furex.View
}

func (g *Game) Update() error {
	g.initOnce.Do(func() {
		g.setupUI()
	})

	width, height := ebiten.WindowSize()
	g.gameUI.UpdateWithSize(width, height)
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	screen.Fill(color.RGBA{0x3d, 0x55, 0x0c, 0xff})
	g.gameUI.Draw(screen)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	g.screenSize.Width = outsideWidth
	g.screenSize.Height = outsideHeight
	return g.screenSize.Width, g.screenSize.Height
}

func NewGame() (*Game, error) {
	game := &Game{}
	return game, nil
}

func (g *Game) setupUI() {
	g.gameUI = &furex.View{
		Width:        g.screenSize.Width,
		Height:       g.screenSize.Height,
		Direction:    furex.Row,
		Justify:      furex.JustifyCenter,
		AlignItems:   furex.AlignItemCenter,
		AlignContent: furex.AlignContentCenter,
		Wrap:         furex.Wrap,
	}

	g.gameUI.AddChild(&furex.View{
		Width:  g.screenSize.Width,
		Height: 50,
		Handler: &Box{
			Color: color.RGBA{0xdd, 0xdd, 0xdd, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Width:  g.screenSize.Width,
		Height: g.screenSize.Height - 50 - 50,
		Handler: &Box{
			Color: color.RGBA{0x81, 0xb6, 0x22, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Width:  g.screenSize.Width,
		Height: 50,
		Handler: &Box{
			Color: color.RGBA{0xff, 0xff, 0xff, 0xff},
		},
	})
}

type Box struct {
	Color color.Color
}

func (b *Box) HandleDraw(screen *ebiten.Image, frame image.Rectangle) {
	ebitenutil.DrawRect(
		screen,
		float64(frame.Min.X),
		float64(frame.Min.Y),
		float64(frame.Size().X),
		float64(frame.Size().Y),
		b.Color,
	)
}

func main() {
	ebiten.SetWindowSize(800, 600)
	ebiten.SetWindowResizingMode(ebiten.WindowResizingModeEnabled)

	game, err := NewGame()
	if err != nil {
		panic(err)
	}

	if err := ebiten.RunGame(game); err != nil {
		panic(err)
	}
}
```

This already includes a `g.gameUI.UpdateWithSize(width, height)` call inside of the `update` function, but it's not clear what updating the parent furex.View object with those sizes really means, or how I could get the child furex.View objects inside of `setupUI` to pick up the new size changes

It looks like all your `UpdateWithSize` function is doing is:
```
// UpdateWithSize the view with modified height and width
func (v *View) UpdateWithSize(width, height int) {
	if !v.hasParent && (v.Width != width || v.Height != height) {
		v.Height = height
		v.Width = width
		v.isDirty = true
	}
	v.Update()
}
```
And nowhere in there does it seem to inform the child views about the new height and width of the parent, so how are they supposed to pick it up?

The only real way I saw to do this was to keep track of the screen size inside of the update function, and if it changed, rerun/recreate all of the work done in the `setupUI` function, which just feels wrong

Am I understanding this correctly/is that the expected way users should have dynamically adjusting child View objects?

**Comment by yohamta** [comment]
@hak33m16 
It seems that the View is not properly configured in your code. Here is the code I tried to fix the issue. Please check if it fixes the problem. Flex Layout is a bit complicated at the first sight, but you can learn it easily [here](https://flexboxfroggy.com/) if you are interested 🙂

```go
package main

import (
	"image"
	"image/color"
	"sync"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
	"github.com/yohamta/furex/v2"
)

type ScreenSize struct {
	Width  int
	Height int
}

type Game struct {
	initOnce   sync.Once
	screenSize ScreenSize
	gameUI     *furex.View
}

func (g *Game) Update() error {
	g.initOnce.Do(func() {
		g.setupUI()
	})

	width, height := ebiten.WindowSize()
	g.gameUI.UpdateWithSize(width, height)
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	screen.Fill(color.RGBA{0x3d, 0x55, 0x0c, 0xff})
	g.gameUI.Draw(screen)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	g.screenSize.Width = outsideWidth
	g.screenSize.Height = outsideHeight
	return g.screenSize.Width, g.screenSize.Height
}

func NewGame() (*Game, error) {
	game := &Game{}
	return game, nil
}

func (g *Game) setupUI() {
	g.gameUI = &furex.View{
		Width:      g.screenSize.Width,
		Height:     g.screenSize.Height,
		Direction:  furex.Column,
		Justify:    furex.JustifyCenter,
		AlignItems: furex.AlignItemStretch,
	}

	g.gameUI.AddChild(&furex.View{
		Height: 50,
		Handler: &Box{
			Color: color.RGBA{0xdd, 0xdd, 0xdd, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Grow: 1,
		Handler: &Box{
			Color: color.RGBA{0x81, 0xb6, 0x22, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Height: 50,
		Handler: &Box{
			Color: color.RGBA{0xff, 0xff, 0xff, 0xff},
		},
	})
}

type Box struct {
	Color color.Color
}

func (b *Box) HandleDraw(screen *ebiten.Image, frame image.Rectangle) {
	ebitenutil.DrawRect(
		screen,
		float64(frame.Min.X),
		float64(frame.Min.Y),
		float64(frame.Size().X),
		float64(frame.Size().Y),
		b.Color,
	)
}

func main() {
	ebiten.SetWindowSize(800, 600)
	ebiten.SetWindowResizingMode(ebiten.WindowResizingModeEnabled)

	game, err := NewGame()
	if err != nil {
		panic(err)
	}

	if err := ebiten.RunGame(game); err != nil {
		panic(err)
	}
}
```

**Comment by hak33m16** [comment]
Unfortunately that also doesn't work, this example renders nothing on the screen:
```
	g.gameUI = &furex.View{
		Width:      g.screenSize.Width,
		Height:     g.screenSize.Height,
		Direction:  furex.Column,
		Justify:    furex.JustifyCenter,
		AlignItems: furex.AlignItemStretch,
	}

	g.gameUI.AddChild(&furex.View{
		Height: 50,
		Handler: &Box{
			Color: color.RGBA{0xdd, 0xdd, 0xdd, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Grow: 1,
		Handler: &Box{
			Color: color.RGBA{0x81, 0xb6, 0x22, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Height: 50,
		Handler: &Box{
			Color: color.RGBA{0xff, 0xff, 0xff, 0xff},
		},
	})
```

It seems like I'm required to specify the Width property on the child items, or it doesn't work, which leads to the same issue when resizing as mentioned before:
```
	g.gameUI = &furex.View{
		Width:      g.screenSize.Width,
		Height:     g.screenSize.Height,
		Direction:  furex.Column,
		Justify:    furex.JustifyCenter,
		AlignItems: furex.AlignItemCenter,
	}

	g.gameUI.AddChild(&furex.View{
		Height: 50,
		Width:  g.screenSize.Width,
		Handler: &Box{
			Color: color.RGBA{0xdd, 0xdd, 0xdd, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Grow:  1,
		Width: g.screenSize.Width,
		Handler: &Box{
			Color: color.RGBA{0x81, 0xb6, 0x22, 0xff},
		},
	})

	g.gameUI.AddChild(&furex.View{
		Height: 50,
		Width:  g.screenSize.Width,
		Handler: &Box{
			Color: color.RGBA{0xff, 0xff, 0xff, 0xff},
		},
	})
```

I'll make my way through the flexbox tutorial, thanks for the link!

**Comment by yohamta** [comment]
I am not sure, but I guess there's still some issue in your code. 
I added an example project for the resizable window. Please download the directory and check if it works on your PC.
https://github.com/yohamta/furex/tree/main/examples/resizable

Below is the screenshot I took on my PC. I think it should be working on your PC as well.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/1475839/211245367-1c13a099-fe67-41b8-a787-d6aac5887542.png">

**Comment by hak33m16** [comment]
Ahhh, I see, looks like I missed that you changed this property:

```diff
@@ -53,7 +53,7 @@ func (g *Game) setupUI() {
                Height:     g.screenSize.Height,
                Direction:  furex.Column,
                Justify:    furex.JustifyCenter,
-               AlignItems: furex.AlignItemCenter,
+               AlignItems: furex.AlignItemStretch,
        }
```

For some reason that makes the difference of whether it displays nothing vs. the child items. Could you help me understand why that is? I know this is more of a flex layout question and less of one related to your library

**Comment by yohamta** [comment]
I am glad that you solved the issue 🙂

Well, the reason that it displayed nothing was that the default value of `Width` is `0` if it is not specified in the View's property. However, when you specify the `AlighItemStretch`, Flexbox Algorithm expands the "size" of the View to the cross-direction. The "size" means the View's `Width` in this case because the `FlexDirection` is specified as `Column` in the parent View. `Column` means vertical direction so cross-direction means horizontal direction.

MDN web docs about flex-layout might be useful for more information.
> stretch
> Flex items are stretched such that the cross-size of the item's margin box is the same as the line while respecting width and height constraints.
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items

**Comment by hak33m16** [comment]
Ah, I guess that makes sense. And so in browsers, it's set up in such a way that it's able to automatically detect the width? I appreciate all the help and the new example, sounds like this can be closed

**Comment by yohamta** [comment]
Thank you for closing the issue. I think it should be working on both browsers and standalone apps.
